//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZirconiumX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class business
    {
        public int ID { get; set; }
        public string BusinessName { get; set; }
        public string BusinessDescription { get; set; }
    }
}
