//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZirconiumX.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BusinessRegistration
    {
        public string BName { get; set; }
        public string BAddress { get; set; }
        public string Category { get; set; }
        public string BType { get; set; }
        public int RNumber { get; set; }
        public Nullable<int> TNumber { get; set; }
        public Nullable<int> CSize { get; set; }
        public string YEstablishment { get; set; }
        public string BDescription { get; set; }
        public string SName { get; set; }
        public string SPosition1 { get; set; }
        public string SEmail1 { get; set; }
        public string SPhoneNo1 { get; set; }
        public string BEmail { get; set; }
        public string Password { get; set; }
        public string ConfirmPassword { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public int ID { get; set; }
    }
}
