//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZirconiumX.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZirconiumEntities : DbContext
    {
        public ZirconiumEntities()
            : base("name=ZirconiumEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<business> businesses { get; set; }
        public virtual DbSet<BusinessLoginDetail> BusinessLoginDetails { get; set; }
        public virtual DbSet<BusinessRegistration> BusinessRegistrations { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<ManagementTeam> ManagementTeams { get; set; }
        public virtual DbSet<UserRegistration> UserRegistrations { get; set; }
        public virtual DbSet<UserLoginDetail> UserLoginDetails { get; set; }
    }
}
